- name: Dotfiles -> pull
  git: repo=git@github.com:ufotsuboi/dotfiles.git dest=/root/.dotfiles accept_hostkey=yes update=yes version=master
  poll: 30

- name: Setup dotfiles
  shell: ./setup.sh
  args:
    chdir: ~/.dotfiles

- name: Change shell
  shell: chsh -s $(grep /zsh$ /etc/shells | tail -1)
